### ISSUE TITLE
Session 4 Report

### ISSUE THREAD

**Issue by LaayaYaghoubi** [Sharif-OS-Lab/session-3-4#4]
Team Name: 96150292-96150127

Student Name of member 1: Laaya Yaghoubi
Student No. of member 1: 96150292

Student Name of member 2: Shayan Masrour
Student No. of member 2: 96150127

- [ ] Read Session Contents.

### Section 4.4.1
- [ ] Investigate the ps command
    1. [ ] 
![Screenshot 2021-11-05 172240](https://user-images.githubusercontent.com/88422443/140538057-58a8fd70-8a94-4aee-afac-9846f5580cac.png)

    
- [ ] Infromation about processes with PID = 1
    1. [ ] Process ID 1 is usually the init process primarily responsible for starting and shutting down the system. Originally, process ID 1 was not specifically reserved for init by any technical measures: it simply had this ID as a natural consequence of being the first process invoked by the kernel.
![Screenshot 2021-11-05 180352](https://user-images.githubusercontent.com/88422443/140538186-3becc007-aade-40dc-9213-e77a6eade653.png)

- [ ] Program using getpid
    1. [ ] ![Screenshot 2021-11-05 180610](https://user-images.githubusercontent.com/88422443/140538237-a3ee1d5e-cd93-4f45-b4f3-615e5b864ed3.png)

### Section 4.4.2

- [ ] Program using getppid
    1. [ ] #include <stido.h>
#include <unistd.h> 

int main(void)
{
pid_t result = fork();
printf("\nfork result %d", result);
printf("\nI am after forking\n");
printf("\nIam process %d", getpid());
printf("\nI am parent process %d", getppid());
return 0;
}
    1. [ ]A parent process is one that creates a child process using a fork() system call. A parent process may have multiple child processes, but a child process only one parent process. On the success of a fork() system call: The Process ID (PID) of the child process is returned to the parent process.
    1. [ ]![Screenshot 2021-11-05 182809](https://user-images.githubusercontent.com/88422443/140575137-48a39794-035a-438f-aea8-0941c4a7b1d1.png)

- [ ] Describe the C program (fork program)
    1. [ ] we fork and get a new process.
we check if a process is the child (ret == 0) or if it is the parent (ret!= 0).
In the child process you get 23.

- [ ] Program showing that memory of the parent and the child is seperate
    1. #include  <stdio.h>
#include  <sys/types.h>

#define   MAX_COUNT  200

void  ChildProcess(void);                /* child process prototype  */
void  ParentProcess(void);               /* parent process prototype */

void  main(void)
{
     pid_t  pid;

     pid = fork();
     if (pid == 0) 
          ChildProcess();
     else 
          ParentProcess();
}

void  ChildProcess(void)
{
     int   i;

     for (i = 1; i <= MAX_COUNT; i++)
          printf("   This line is from child, value = %d\n", i);
     printf("   * Child process is done *\n");
}

void  ParentProcess(void)
{
     int   i;

     for (i = 1; i <= MAX_COUNT; i++)
          printf("This line is from parent, value = %d\n", i);
     printf("* Parent is done *\n");
}
When the main program executes fork(), an identical copy of its address space, including the program and all data, is created. System call fork() returns the child process ID to the parent and returns 0 to the child process. The following figure shows that in both address spaces there is a variable pid. The one in the parent receives the child's process ID 3456 and the one in the child receives 0.

- [ ] Program printing different messages for parent and child process
    1. [ ] #include <stdio.h>
#include <unistd.h>

int main(void)
{
pid_t pid;
printf("I am the parent process & pid is:%d.\n",getpid());
printf("before forking\n");
pid = fork();
pritnf("after forking\n");
if(pid == 0)
{
printf("i am the child process and pid is:%d.\n", getpid());
}
else if (pid>0)
{
printf("i am the parent process and pid is: %d.\n", getpid());
}
else if (pid == -1)
{
printf("Error fork failed\n");
}
return 0;
}
![Screenshot 2021-11-05 194414](https://user-images.githubusercontent.com/88422443/140543664-c879a499-e8d3-409a-8f4f-ed83d7e284ff.png)

- [ ] Program for the last task of this section
    1. [ ] #include <stdio.h>
#include <unistd.h>

int main(void)
{
pid_t pid;
printf("before forking\n");
printf("I am the parent process & pid is:%d.\n",getpid());
pid = fork();
printf("after first forking\n");
if(pid == 0)
{
printf("i am the child process and pid is:%d.\n", getpid());
}
else if (pid>0)
{
printf("i am the parent process and pid is: %d.\n", getpid());
}
else if (pid == -1)
{
printf("Error fork failed\n");
}
pid = fork();
printf("after second forking\n");
if(pid == 0)
{
printf("i am the child process and pid is:%d.\n", getpid());
}
else if (pid>0)
{
printf("i am the parent process and pid is: %d.\n", getpid());
}
else if (pid == -1)
{
printf("Error fork failed\n");
}
return 0;
}
![Screenshot 2021-11-05 195726](https://user-images.githubusercontent.com/88422443/140545518-f82995f8-45ba-4b6a-8a76-78f0d08cb564.png)

    1. [ ] In Linux, a daemon is typically created by forking twice with the intermediate process exiting after forking the grandchild. This has the effect of orphaning the grandchild process. As a result, it becomes the responsibility of the OS to clean up after it if it terminates. The reason has to do with what are known as zombie processes which continue to live and consume resources after exiting because their parent, who'd normally be responsible for the cleaning up, has also died.

## Section 4.4.3

- [ ] Program using `wait` and counting from 1 to 100
    1. #include <stdio.h>
#include <sys/wait.h>
#include <unistd.h>

int main()
{
int ret = fork();
if(ret == 0) {
int i;
for(i=1; i<=100; i++)
{
printf("THIS LINE IS FROM CHILD, value = %d\n", i);
printf("\nchild process is done\n")
}
}
else{
int rc = 0;
wait(&rc);
printf("return code is %d\n",WEXITSTATUS(rc));
int i;
for(i=1; i<=100; i++)
{
printf("THIS LINE IS FROM PARENT, value = %d\n", i);
printf("\nchild process is done\n")
}
}
return 0;
}
![Screenshot 2021-11-05 194655](https://user-images.githubusercontent.com/88422443/140546537-ce75c1b7-fac3-4ad8-94e3-5b0c63501e15.png)

    1. [ ] All  of  these  system  calls  are used to wait for state changes in a
       child of the calling process, and obtain information about  the  child
       whose  state  has  changed.   A  state change is considered to be: the
       child terminated; the child was stopped by a signal; or the child  was
       resumed  by a signal.  In the case of a terminated child, performing a
       wait allows the system to release the resources  associated  with  the
       child;  if  a wait is not performed, then the terminated child remains
       in a "zombie" state.

       If a child has already changed state, then these calls return  immedi‐
       ately.   Otherwise, they block until either a child changes state or a
       signal handler interrupts the call (assuming that system calls are not
       automatically  restarted  using  the SA_RESTART flag of sigaction(2)).
       In the remainder of this page, a child whose  state  has  changed  and
       which  has  not  yet  been waited upon by one of these system calls is
       termed waitable.

- [ ] Program showing process adoption
    1. #include <stdio.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <unistd.h>

int main()
{
pid_t pid;
printf("i am the original process with PID %d and PPID %d.\n", getpid(),getppid());
pid = fork();
if (pid> 0)
{
printf("i am the parent with PID %d and PPID%d.\n", getpid(),getppid());
printf("my child's PID is %d\n", pid);
}
else if (pid ==0)
{
sleep(4);
printf("i'm the child with PID %d and PPID %d.\n", getpid(),getppid());
}
printf("PID %d terminates.\n", getpid());
printf("PID %d terminates.\n", getppid());
}
    1. 
![Screenshot 2021-11-05 203848](https://user-images.githubusercontent.com/88422443/140550821-3512f1c1-8463-4e7e-abb4-e33348e5f2d4.png)

### Section 4.4.4

- [ ] Describe following commands/APIs:
    1. The exec subroutine, in all its forms, executes a new program in the calling process. The exec subroutine does not create a new process, but overlays the current program with a new one, which is called the new-process image. The new-process image file can be one of three file types:
An executable binary file in XCOFF file format.
An executable text file that contains a shell procedure (only the execlp and execvp subroutines allow this type of new-process image file).
A file that names an executable binary file or shell procedure to be run.
    1.  execl() system function takes the path of the executable binary file (i.e /bin/ls) as the first and second arguement.then the arguement (i.e -lh, /home) that you want to pass to the executable followed by NULL. Then execl() system function runs the command and prints the output.
    1. The execvp() function is the same with execv() but in its parameter, it gets the file name which is in the PATH environment variable
    1.The execlp() system call duplicates the actions of the shell in searching for an executable file if the specified file name does not contain a slash (/) character. … The execlp system call can be used when the number of arguements to the new program is known at compile time.

- [ ] Program which forks and executues `ls` command
    1. [ ]
![Screenshot 2021-11-05 235349](https://user-images.githubusercontent.com/88422443/140574150-32022a2d-15b0-427e-affc-a4f5affe59d0.png)

    1. [ ] ![Screenshot 2021-11-05 235501](https://user-images.githubusercontent.com/88422443/140574168-acb994c6-7982-4b2f-95eb-98edb2b9348f.png)

## Source Code Submission

please submit all your codes in a zip file

 - [ ]
[codes.zip](https://github.com/Sharif-OS-Lab/session-3-4/files/7488738/codes.zip)

**Comment by amirhossein1376** [comment]
**80/100**
